name: Sync Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull, Tag and Push
        run: |
          # کشیدن ایمیج از داکر هاب (بسیار پایدارتر)
          docker pull sanaei/3x-ui:latest
          
          # تغییر نام به نام کاربری داکر شما
          docker tag sanaei/3x-ui:latest ${{ secrets.DOCKER_USERNAME }}/lib-core:latest
          
          # آپلود در اکانت شما
          docker push ${{ secrets.DOCKER_USERNAME }}/lib-core:latest
